version: '3.8'
services:
  db:
    image: postgres:15
    container_name: weighthub-db
    restart: always
    environment:
      # 这里的配置必须和你的 .env 文件对应
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: weighthub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: